# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-28 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import melanieweb.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=melanieweb.models.get_image_path)),
            ],
        ),
    ]
